[package]
name = "game_score"
version = "0.1.0"
authors = ["tetsuya-yamamoto <yamamoto_tetsuya@cyberagent.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
